baseURL = '/'
languageCode = 'en-us'
title = "Yunzhi's Archive"
theme = 'PaperMod'
defaultContentLanguage = "en"
enableInlineShortcodes = true
enableEmoji = true
canonifyURLs = true

[pagination]
  pagerSize = 10

[params]
  author = "Yunzhi"
  ShowToc = true
  ShowReadingTime = true
  ShowPostNavLinks = false
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "dark"
  disableThemeToggle = false
  images = ["images/Irene_Halloween.png"]
  disableSpecial1stPost = true

# config.toml
[minify]
  disableJSON = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[menu]

[[menu.main]]
  identifier = "home"
  name = "ğŸ§™ğŸ»â€â™€ï¸Home"
  url = "/"
  weight = 0


# ğŸ§™ğŸ»â€â™€ï¸ é¦–é¡µ
[[menu.main]]
  identifier = "fiction"
  name = "ğŸ–‹Fiction"
  url = "/fiction/"
  weight = 1

# å­èœå•ï¼šTo Serein
[[menu.main]]
  identifier = "to-serein"
  name = "To Serein"
  url = "/fiction/to-serein/"
  weight = 1
  parent = "fiction"

[[menu.main]]
  identifier = "to-serein-main"
  name = "Main Story"
  url = "/fiction/to-serein/main/"
  weight = 1
  parent = "to-serein"

[[menu.main]]
  identifier = "to-serein-extras"
  name = "Extras"
  url = "/fiction/to-serein/extras/"
  weight = 2
  parent = "to-serein"

# å­èœå•ï¼šThe Black Hole Office
[[menu.main]]
  identifier = "black-hole-office"
  name = "The Black Hole Office"
  url = "/fiction/black-hole-office/"
  weight = 2
  parent = "fiction"

# å­èœå•ï¼šShort Stories
[[menu.main]]
  identifier = "short-stories"
  name = "Short Stories"
  url = "/fiction/shorts/"
  weight = 3
  parent = "fiction"


# ğŸ¨ Gallery åŠå…¶å­èœå•
[[menu.main]]
  identifier = "gallery"
  name = "Gallery"
  url = "/gallery/"
  weight = 10

[[menu.main]]
  identifier = "gallery-serein"
  name = "To Serein"
  url = "/gallery/to-serein/"
  weight = 1
  parent = "gallery"

[[menu.main]]
  identifier = "gallery-blackhole"
  name = "The Black Hole Office"
  url = "/gallery/black-hole-office/"
  weight = 2
  parent = "gallery"

[[menu.main]]
  identifier = "gallery-doodle"
  name = "Doodle"
  url = "/gallery/doodle/"
  weight = 3
  parent = "gallery"

# ğŸ“œ å…¶ä»–èœå•
[[menu.main]]
  identifier = "witch-lore"
  name = "Witch Lore"
  url = "/witch-lore/"
  weight = 11

[[menu.main]]
  identifier = "music"
  name = "Music"
  url = "/music/"
  weight = 12

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 13











